name: "n0s1"

on:
  push:
    branches: [ "ms/test" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 13 * * 1'

jobs:
  jira_secret_scanning:
    runs-on: [ubuntu-latest]
    steps:
      - uses: spark1security/n0s1-action@main
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          scan-target: 'jira_scan'
          user-email: 'marcelo@spark1.us'
          platform-url: 'https://spark1us.atlassian.net'
          report-format: "sarif"
          report-file: "jira_secret_report.sarif"
          timeout: 5
          limit: 100
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "jira_secret_report.sarif"
          category: jira_secret_report